import base64
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import GMAIL_SENDER


class GmailAction:
    def __init__(self, service):
        self.service = service

    def send_procurement_alert(self, sku: str, stock: int, days_cover: float, order_qty: int) -> dict:
        subject = f"URGENT STOCKOUT ALERT - {sku} | StockSense"
        html_body = f"""
        <html><body style="font-family: Arial, sans-serif; color: #333;">
        <div style="background:#d32f2f;color:white;padding:16px;border-radius:4px;">
            <h2 style="margin:0;">&#9888; URGENT STOCKOUT ALERT</h2>
        </div>
        <div style="padding:16px;">
            <table style="width:100%;border-collapse:collapse;">
                <tr><td style="padding:8px;font-weight:bold;">SKU</td><td style="padding:8px;">{sku} - Wireless Earbuds Pro</td></tr>
                <tr style="background:#fafafa;"><td style="padding:8px;font-weight:bold;">Current Stock</td><td style="padding:8px;">{stock} units</td></tr>
                <tr><td style="padding:8px;font-weight:bold;">Days of Cover</td><td style="padding:8px;color:#d32f2f;font-weight:bold;">{days_cover} days</td></tr>
                <tr style="background:#fafafa;"><td style="padding:8px;font-weight:bold;">Recommended Order</td><td style="padding:8px;">{order_qty} units</td></tr>
                <tr><td style="padding:8px;font-weight:bold;">Estimated Cost</td><td style="padding:8px;">PKR {order_qty * 49:,}</td></tr>
            </table>
            <p style="margin-top:16px;padding:12px;background:#fff3e0;border-left:4px solid #ff9800;">
                <strong>Action Required:</strong> Place emergency order immediately to avoid stockout.
                Contact Shenzhen Electronics Co. Lead time: 5-7 business days.
            </p>
            <p style="color:#999;font-size:12px;">Generated by StockSense AI Pipeline</p>
        </div>
        </body></html>
        """

        message = MIMEMultipart("alternative")
        message["Subject"] = subject
        message["From"] = GMAIL_SENDER
        message["To"] = GMAIL_SENDER
        message.attach(MIMEText(html_body, "html"))

        encoded = base64.urlsafe_b64encode(message.as_bytes()).decode()
        sent = self.service.users().messages().send(
            userId="me", body={"raw": encoded}
        ).execute()

        return {"status": "sent", "message_id": sent.get("id")}
